Default: &defaults
  host: "localhost"
  port: 3000
  approot: "http://localhost:3000"
  copyright: "2012-2014 Snowdrift.coop"
  source: "https://gitorious.org/snowdrift/snowdrift"
  githubrepo: "dlthomas/snowdrift"
  siteproject: "snowdrift"
  #analytics: UA-YOURCODE

Development:
  host: "*"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://192.168.1.2:4003"
  port: 4003
  <<: *defaults
